spring:
  cloud:
    config:
      server:
        git:
          uri:  https://github.com/vgrysh/config.git
          basedir: C:/CloudConfigServer-1.0.0/repo/
          clone-on-start: true

server:
  port: 8016